#
# This is an example configuration file.
#
scenario_to_monitor = ""

# Directory where the Kovaak's stats files are stored.
# stats_dir = "C:/SteamLibrary/steamapps/common/FPSAimTrainer/FPSAimTrainer/stats"
stats_dir = "Change me!"

# Only care about runs within the last N days
within_n_days = 30

# Limit to the top N scores
top_n_scores = 5

# How often to poll for updates (in milliseconds)
polling_interval = 1000  # 1 second

# Port to use for the backend server.
port = 8080

# How many decimal places to round the Sensitivity. The smaller the number, the more the Sensitivities are grouped.
# For example, if Sensitivity=40.159, rounded to one digit -> 40.2
sens_round_decimal_places = 1
